### ISSUE TITLE
Gradio Error when Executing openai.ChatCompletion

### ISSUE THREAD

**Issue by arnoldapg** [Farzad-R/LLM-Zero-to-Hundred#18]
On RAG-GPT

Traceback (most recent call last):
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\gradio\routes.py", line 763, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\src\utils\chatbot.py", line 66, in respond
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DATA\Downloads\RAG-Clone\LLM-Zero-to-Hundred\RAG-GPT\RAG-GPT\Lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

Hi, I have this error, I think it is in gradio packages error. I've tried upgrade all requirements but still error like this. And when I tried to install specific version, like openai 0.28, it gave another error. Please help me fix this

**Comment by Farzad-R** [comment]
The error is occurring due to updates in the OpenAI library. Since I originally developed the project, OpenAI has modified some of its functions and classes, so you’ll need to adjust the code to work with the latest version.

Alternatively, you can:

Downgrade the library using:
```
pip install openai==0.28
```
Or run the OpenAI migration tool:

```
openai migrate
```
This will upgrade your codebase to the 1.0.0 interface, though I haven't tested this myself, so some manual adjustments may still be necessary.
